version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    networks:
      - pg-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: rohitverma1569@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Password
    ports:
      - "5051:80"
    networks:
      - pg-net
    depends_on:
      - postgres

networks:
  pg-net:

volumes:
  postgres-data:
